// ──── Regime Fiscale (codici FatturaPA) ──────────────────
export const RegimeFiscale = {
  ORDINARIO: 'ORDINARIO',                                     // RF01
  CONTRIBUENTI_MINIMI: 'CONTRIBUENTI_MINIMI',                  // RF02
  FORFETTARIO: 'FORFETTARIO',                                  // RF19
  AGRICOLTURA_REDDITI_DOMINICALI: 'AGRICOLTURA_REDDITI_DOMINICALI', // RF04
  VENDITA_SALI_TABACCHI: 'VENDITA_SALI_TABACCHI',              // RF05
  COMMERCIO_FIAMMIFERI: 'COMMERCIO_FIAMMIFERI',                // RF06
  EDITORIA: 'EDITORIA',                                        // RF07
  GESTIONE_SERVIZI_TELEFONIA: 'GESTIONE_SERVIZI_TELEFONIA',    // RF08
  RIVENDITA_DOCUMENTI_TRASPORTO: 'RIVENDITA_DOCUMENTI_TRASPORTO', // RF09
  INTRATTENIMENTI_GIOCHI: 'INTRATTENIMENTI_GIOCHI',            // RF10
  AGENZIE_VIAGGI_TURISMO: 'AGENZIE_VIAGGI_TURISMO',            // RF11
  AGRITURISMO: 'AGRITURISMO',                                  // RF12
  VENDITE_PORTA_A_PORTA: 'VENDITE_PORTA_A_PORTA',              // RF13
  RIVENDITORE_BENI_USATI: 'RIVENDITORE_BENI_USATI',            // RF14
  AGENZIE_VENDITE_ASTE_PUBBLICHE: 'AGENZIE_VENDITE_ASTE_PUBBLICHE', // RF15
  IVA_PER_CASSA: 'IVA_PER_CASSA',                              // RF16
  ALTRO: 'ALTRO',                                              // RF18
} as const;
export type RegimeFiscale = (typeof RegimeFiscale)[keyof typeof RegimeFiscale];

/** Mappatura regime fiscale → codice FatturaPA */
export const REGIME_FISCALE_TO_CODE: Record<RegimeFiscale, string> = {
  ORDINARIO: 'RF01',
  CONTRIBUENTI_MINIMI: 'RF02',
  FORFETTARIO: 'RF19',
  AGRICOLTURA_REDDITI_DOMINICALI: 'RF04',
  VENDITA_SALI_TABACCHI: 'RF05',
  COMMERCIO_FIAMMIFERI: 'RF06',
  EDITORIA: 'RF07',
  GESTIONE_SERVIZI_TELEFONIA: 'RF08',
  RIVENDITA_DOCUMENTI_TRASPORTO: 'RF09',
  INTRATTENIMENTI_GIOCHI: 'RF10',
  AGENZIE_VIAGGI_TURISMO: 'RF11',
  AGRITURISMO: 'RF12',
  VENDITE_PORTA_A_PORTA: 'RF13',
  RIVENDITORE_BENI_USATI: 'RF14',
  AGENZIE_VENDITE_ASTE_PUBBLICHE: 'RF15',
  IVA_PER_CASSA: 'RF16',
  ALTRO: 'RF18',
};
